export const fakeMenuData = [
  {
    id: 1,
    name: "Döner",
    price: 500, // in cents,
    calories: 800,
    ingredients: ["brot", "fleisch", "salat", "soße"],
  },
  {
    id: 2,
    name: "Pizza Margherita",
    price: 1200,
    calories: 620,
    ingredients: ["teig", "tomatensoße", "mozzarella", "basilikum"],
  },
  {
    id: 3,
    name: "Burger mit Pommes",
    price: 1350,
    calories: 850,
    ingredients: ["brioche-brötchen", "rindfleisch", "käse", "salat", "pommes"],
  },
  {
    id: 4,
    name: "Sushi Set",
    price: 1680,
    calories: 480,
    ingredients: ["reis", "lachs", "thunfisch", "nori", "wasabi", "ingwer"],
  },
  {
    id: 5,
    name: "Pad Thai",
    price: 1150,
    calories: 710,
    ingredients: [
      "reisnudeln",
      "garnelen",
      "erdnüsse",
      "sojasprossen",
      "tamarinde",
    ],
  },
  {
    id: 6,
    name: "Tacos al Pastor",
    price: 980,
    calories: 650,
    ingredients: [
      "mais-tortillas",
      "schweinefleisch",
      "ananas",
      "zwiebeln",
      "koriander",
    ],
  },
  {
    id: 7,
    name: "Pasta Carbonara",
    price: 1080,
    calories: 720,
    ingredients: [
      "spaghetti",
      "speck",
      "eier",
      "parmesan",
      "schwarzer pfeffer",
    ],
  },
  {
    id: 8,
    name: "Falafel Teller",
    price: 890,
    calories: 580,
    ingredients: ["falafel", "hummus", "tabouleh", "pita-brot", "tahini"],
  },
  {
    id: 9,
    name: "Chicken Tikka Masala",
    price: 1250,
    calories: 760,
    ingredients: [
      "hähnchen",
      "tomaten-curry-soße",
      "basmati-reis",
      "naan-brot",
    ],
  },
  {
    id: 10,
    name: "Pho Bo",
    price: 1150,
    calories: 520,
    ingredients: [
      "reisnudeln",
      "rinderbrühe",
      "rindfleisch",
      "kräuter",
      "limette",
    ],
  },
  {
    id: 11,
    name: "Paella Valenciana",
    price: 1580,
    calories: 680,
    ingredients: ["bomba-reis", "hähnchen", "kaninchen", "bohnen", "safran"],
  },
];
